TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.27
  min_vel_x: 0.1

  max_vel_y: 0.2
  min_vel_y: 0.07

  y_vels: [-0.3, -0.1, 0.1, 0.3]

  max_vel_theta:  1.7
  min_vel_theta: -1.7 
  min_in_place_vel_theta: 1.7

  acc_lim_x: 1.0 # X 加速限制
  acc_lim_y: 0.5 # Y 加速限制
  acc_lim_theta: 0.5 # 角速度加速限制（弧度/秒）

# Goal Tolerance Parameters，目标公差
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  latch_xy_goal_tolerance: true # If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.

# Differential-drive robot configuration
# 是否是全向移动机器人
  holonomic_robot: true

# Forward Simulation Parameters，前进模拟参数，可通过调试如下参数，使局部路径规划更贴合全局路径规划
  sim_time: 0.8  # 提高sim_time值可使局部路径规划更符合全局路径规划
  vx_samples: 18  
  vtheta_samples: 20
  sim_granularity: 0.05

  occdist_scale: 0.01 # The weighting for how much the controller should attempt to avoid obstacles; default:0.01
  # publish_cost_grid_pc: true