obstacle_range: 2.5
raytrace_range: 2.5
footprint: [[-0.52, -0.14], [-0.52, 0.14],[0.30, 0.14],[0.30, -0.14]]
# robot_radius: 0.01
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: unilidar_lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# point_cloud2_sensor: {sensor_frame: unilidar_lidar, data_type: PointCloud2, topic: /unilidar/cloud, marking: true, clearing: true}


# plugins:
#   - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
#   - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
#   - {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}

# voxel_layer:
#   enabled: true
#   origin_z: 0.0
#   z_resolution: 0.05
#   z_voxels: 10
#   unknown_threshold: 0
#   mark_threshold: 2
#   publish_voxel_map: true
#   combination_method: 0
#   observation_sources: point_cloud2_sensor
#   output_points:
#     data_type: PointCloud2
#     topic: voxel_points
#     marking: true
#     clearing: true
#     obstacle_range: 1.90
#     raytrace_range: 2.00
#     min_obstacle_height: 0.00
#     max_obstacle_height: 3.00
#     mark_threshold: 3
#     observation_persistence: 2.0

# obstacle_layer:
#   enabled: true
#   origin_z: 0.0
#   observation_sources: point_cloud2_sensor

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: unilidar_lidar,
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }
 
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.36
 
static_layer:
  enabled: true
