local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.025
  transform_tolerance: 2
  plugins:
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}