obstacle_range: 2.5
raytrace_range: 2.5
footprint: [[-0.1, -0.45], [-0.1, 0.45],[0.1, 0.45],[0.1, -0.45]]
# robot_radius: 0.01
inflation_radius: 0.2
transform_tolerance: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: unilidar_lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}