global_costmap:
  global_frame: map
  robot_base_frame: unilidar_lidar
  update_frequency: 5.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 50
  height: 50
  resolution: 0.025
  transform_torlence: 2