local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6
  height: 6
  resolution: 0.025
  transform_tolerance: 2