local_costmap:
  global_frame: map
  robot_base_frame: unilidar_lidar
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.025
  transform_tolerance: 2