scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.57
    max_x: 0.3
    min_y: -0.21
    max_y: 0.21
    min_z: 0
    max_z: 0.05
- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 1
    max_range: 1
    max_range_difference: 0.15
    filter_window: 4